# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Fabricante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Franquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datainsercao', models.DateTimeField(blank=True, db_column=b'dataInsercao', default=django.utils.timezone.now, null=True)),
                ('valorcompraunitario', models.FloatField(db_column=b'valorCompraUnitario')),
                ('valorvendaunitario', models.FloatField(db_column=b'valorVendaUnitario')),
                ('quantidadetotal', models.IntegerField(db_column=b'quantidadeTotal')),
                ('quantidadevendida', models.IntegerField(blank=True, db_column=b'quantidadeVendida', null=True)),
            ],
            options={
                'db_table': 'Lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('precoatual', models.FloatField(blank=True, db_column=b'precoAtual', null=True)),
            ],
            options={
                'db_table': 'Produto',
                'managed': False,
            },
        ),
    ]
