# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-12 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoApp', '0002_categoria_fabricante_franquia_lote_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='permissoes',
        ),
    ]
