# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoApp', '0003_auto_20170812_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoteVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valorvendaunitario', models.FloatField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestaoApp.Lote')),
            ],
            options={
                'db_table': 'LoteVenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorCredito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parcelas', models.IntegerField(blank=True, null=True)),
                ('valorDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorMoeda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descontoPorcentagem', models.IntegerField(blank=True, null=True)),
                ('descontoValor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestaoApp.Cliente')),
            ],
            options={
                'db_table': 'Venda',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lotevenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestaoApp.Venda'),
        ),
    ]
