# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoApp', '0004_auto_20170813_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadetotal', models.IntegerField(db_column=b'quantidadeTotal')),
                ('quantidadevendida', models.IntegerField(blank=True, db_column=b'quantidadeVendida', default=0, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestaoApp.Produto')),
            ],
            options={
                'db_table': 'Estoque',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstoqueVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valorvendaunitario', models.FloatField()),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestaoApp.Estoque')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GestaoApp.Venda')),
            ],
            options={
                'db_table': 'EstoqueVenda',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='lotevenda',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='lotevenda',
            name='venda',
        ),
        migrations.DeleteModel(
            name='LoteVenda',
        ),
    ]
