from categoriaView import *
from categoriaAutocompleteView import *
from clienteView import *
from clienteAutocompleteView import *
from fabricanteView import *
from fabricanteAutocompleteView import *
from franquiaView import *
from franquiaAutocompleteView import *
from indexView import *
#from loteAutocompleteView import *
from loteView import *
from produtoView import *
from produtoAutocompleteView import *
#from estoqueView import *
#from vendaView import *
#from clienteAutocompleteView import *